# HW 7 - Libraries + Modules
ULAB - Physics and Astronomy Division \
Due **Wednesday, November 6th, 2024 at 11:59pm** on Gradescope

--------------------------------------------------------------

## Module vs. Package vs. Library
### Module
A **module** is a single file containing Python code (typically ending in a `.py` extension) that contains functions and variables. 
- They can be imported into other Python files or notebooks
- You use modules to organize code into smaller, reuseable parts
- Ex: `even_sum.py` that we created during lecture.

*You will create your OWN module for this homework and use that we made during class.*

### Package
A **package** is a group of modules, organized like a directory. 
- A package requires a special `__init__.py` file to tell Python that the ENTIRE directory is something you would like to import.
- Packages can contain sub-pacakges
- Ex: `BAGLE_Microlensing` is an example of a package (if you are in Dex's group, this should be familar to you). Or you could think of `paarti` if you are in Brianna's group.

*You will NOT be working with a package for this homework.*

### Library
A **library** is a much broader term that also refers to a collection of modules (like a package) but a library can also contain mulitple packages. 
- Libraries serve a much wider range of functionality for
- Programmers use packages to have ready-to-go tools that can be used for data manipulation, web development, machine learning or simulations.
- Ex: `numpy` is a very common library. Later in this course we will also be working some of the following libraries `matplotlib`, `scipy`, and `astropy`, `pandas`, etc

*You WILL be working with the extensive numpy library for this homework!*

--------------------------------------------------------------

# 1 NumPy
**NumPy** (aka Numerical Python) is a library that was designed for caring out computations in Python. 

We did not have a ton of time to work through examples during class, so I will ask that you check out this website for more information: https://numpy.org/doc/ 

Before we can work through any problems, you need to call the following in your notebook:

In [252]:
import numpy as np

## 1.1 Lists vs. Arrays
*When I first started working with NumPy I didn't understand what was so special about arrays. This homework problem should help illustrate the difference. Make sure to follow each step and follow good coding practices.*

1) Make a list called `my_list` and make an array called `my_arr` with the same values. There is an example below, but don't copy mine! Ex:
```
my_list = [11, 12, 13, 14, 15]
my_arr = np.array([11, 12, 13, 14, 15])
```
*Notice that to use the `numpy` package we had to call its short cut `np` and then call upon its funciton `.array()`. This is similar to working with a built-in python function like `.append()`.*

In [253]:
# Your code here

my_list = [1, 2, 3, 5, 8, 13]
my_arr = np.array([1, 2, 3, 5, 8, 13])

2) Multiply `my_list` by 4 and multiply `my_arr` by 4. Print the results. Describe what happens in a comment.

In [254]:
# Your code here

print(my_list * 4)
print(my_arr * 4)

## Multiplication of a list just concatenates the list, thus number of elements increase by 4.
## Multiplication of an array returns another array with same number of elements, each element multiplied by 4

[1, 2, 3, 5, 8, 13, 1, 2, 3, 5, 8, 13, 1, 2, 3, 5, 8, 13, 1, 2, 3, 5, 8, 13]
[ 4  8 12 20 32 52]


3) Add `my_list` with `my_list`. Add `my_arr` with `my_arr`. Add `my_list` with `my_arr`. Print the results. Describe what happens in a comment.

In [255]:
# Your code here

print(my_list + my_list)
print(my_arr + my_arr)

## Addition of two lists returns concatenation of two lists, as if multipling single list by 2.
## Addition of two arrays returns the same dimension array where its element is the sum of elements in the same index.

[1, 2, 3, 5, 8, 13, 1, 2, 3, 5, 8, 13]
[ 2  4  6 10 16 26]


4) Subtract `my_list` with `my_list`. Subtract `my_arr` with `my_arr`. Subtract `my_list` with `my_arr`. Print the results. Describe what happens in a comment.

In [256]:
# Your code here

print(my_arr - my_arr)
print(my_list - my_arr)
try: 
    print(my_list - my_list)
except TypeError:
    print("This does not work!")

## Subtracting array from array is the same dimensional array with each element being the difference of elements in the same index.
## Subtracting array from the list returns the same result
## Subtracting list from the another list is NOT defined in python, gives rise to TypeError

[0 0 0 0 0 0]
[0 0 0 0 0 0]
This does not work!


5) Multiply `my_list` with `my_list`. Multply `my_arr` with `my_arr`. Multiply `my_list` with `my_arr`. Print the results. Describe what happens in a comment.

In [257]:
# Your code here

print(my_arr * my_arr)
print(my_list * my_arr)
try: 
    print(my_list * my_list)
except TypeError:
    print("This does not work!")

## Multypling array by array gives the same dimensional array with each element being the product of elements in the same index.
## Multypling the list by array returns the same result
## Multypling list by another list is NOT supported in python, again giving rise to TypeError

[  1   4   9  25  64 169]
[  1   4   9  25  64 169]
This does not work!


7) Divide `my_list` with `my_list`. Divide `my_arr` with `my_arr`. Divide `my_list` with `my_arr`. Print the results. Describe what happens in a comment.

In [258]:
# Your code here

print(my_arr / my_arr)
print(my_list / my_arr)
try: 
    print(my_list / my_list)
except TypeError:
    print("This does not work!")

## Dividing array by array gives the same dimensional array with each element being the division of elements in the same index.
## Dividing the list by array returns the same result
## Dividing list by another list is also NOT defined in python, again giving rise to TypeError

[1. 1. 1. 1. 1. 1.]
[1. 1. 1. 1. 1. 1.]
This does not work!


8) After working through this problem, in at least two sentences, describe the difference between a list and an array.

In [259]:
# Your code here

# List cannot undergo subtraction, multiplication, and division between themselves.
# Addition of lists returns just a concatenation of the lists, whereas addition of arrays return performs addition that we know.
# Similarly, list can only be multiplied by an integer, and its result is also a concatenation of corresponding numbers of list.
# On the other hand, array can be multiplied by any int or float which gives that number times elements of the array.

## 1.2 Nested List and Multi-Dimensional Arrays
A **nested list** is when you have a list as an element for a list. Example:
```
nested_list = [[1, 2, 3], [4, 5, 6]]
```

A **multi-dimensional array** is essentially a nested list, but it contains the properties of a matrix. Example:
```
multi_d_array = np.array([[1, 2, 3], [4, 5, 6]])
```

Go to this website for more information on NumPy: https://www.w3schools.com/python/numpy/default.asp

Write a **function** that takes in a two-dimensional array. Example:

```
arr3 = np.array([[2, 4, 6], [8, 10, 12], [14, 16, 18]])
```

and then returns the second value in each row. Example:

```
[4, 10, 16]
```

In [260]:
# Your code here

# This is a 3x3 array that I will going to use
two_dim_array = np.array([[6, 78, 45], [6, 5, 45], [87, 92, 6]])


# Function that takes an array as argument
def second_val_row(array):

    # This is a list that will store the second value of each row
    second_val_list = []

    # Iterate over each lists (rows)
    for row in array:
        # Append the 1st index number (2nd value)
        second_val_list.append(row[1])

    return second_val_list


print(second_val_row(two_dim_array)) # It works!

[78, 5, 92]


In 2-3 sentences, describe what section of the website helped you write your function. 

In [261]:
# Your comment here

# Array indexing part was a key to solve this question.
# Also, iterating over array section was helpful to write a for-loop.

How would you take a nested list and return the second value in each row? Explain in 2-3 sentences and show an example.

In [262]:
# Taking a nested list and doing the same job will require the exactly same process.
# This is because nested list is a list of lists, and multy_d_array is also a list of lists.
# One difference is that lists in multy_d_array are arranged vertically.
# However, this does not affect the process of iteration.
# Will show this by calling the exactly same function above, but giving nested list instead as its argument.

my_nested_list = [[6, 78, 45], [6, 5, 45], [87, 92, 6]]

print(second_val_row(my_nested_list)) # It works!

[78, 5, 92]


## 1.3 Up to You!
With the website I just gave you: https://www.w3schools.com/python/numpy/default.asp

I recommend working through the examples they provide (you don't have to do all of them, but a few would be good). It will help you build an intuition for numpy. It won't take very long, there are only a couple of examples per section.

Write you own **function** that follows the theme of one of the sections (i.e. array reshaping, array filter, random intro, etc). For example, if you are curious about the section "**NumPy Creating Arrays**" you could write a function that creates a multi-dimensional array.

```

>>> def make_multi_dimensional_array(one_d_array, dimensions):
...     # Creates a multi-dimensional array
...     # Your code here
...     return # Your code here

>>> my_one_d_array = [2, 4, 6, 8]
>>> my_dimension = 10
>>> ten_d_array = make_multi_dimensional_array(my_one_d_array, my_dimension)
>>> print(ten_d_array)
[[[[[[[[[[2 4 6 8]]]]]]]]]]

```

Your function should be more detailed than the example I gave you. Include at least one of the following: 
- a conditional statement
- an assignment operator
- a loop (`for` or `while`)
- `if`, `elif`, `else`, statement

In [263]:
# Your code here

my_array = np.arange(1, 100)

# Function that prints out multiples of ANY integer in a given list
def any_int_multiple_finder(array, integer):
    # This will return a tuple that contains array of the index of integer multiples in its 0th index
    int_index_list = np.where(array%integer == 0)[0]

    int_multiple_list = []
    # Iterate over the array just made to print out actual values in the given array
    for index in int_index_list:
        int_multiple_list.append(array[index])

    return int_multiple_list

print(any_int_multiple_finder(my_array, 5))  # Multiples of 5
print(any_int_multiple_finder(my_array, 7))  # Multiples of 7
print(any_int_multiple_finder(my_array, 9))  # Multiples of 9
print(any_int_multiple_finder(my_array, 17))  # Multiples of 17

[5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90, 95]
[7, 14, 21, 28, 35, 42, 49, 56, 63, 70, 77, 84, 91, 98]
[9, 18, 27, 36, 45, 54, 63, 72, 81, 90, 99]
[17, 34, 51, 68, 85]


In the section you took inspiration from, show all of the examples below. Follow good coding practices and give at least two test cases for each example. Don't forget comments! \
\
*For my example, I took inspiration from **NumPy Creating Arrays** so I would show following examples with DIFFERENT test cases: Create a NumPy ndarray Object, Dimensions in Arrays ,0-D Arrays, 1-D Arrays, 2-D Arrays, 3-D Arrays, Check Number of Dimensions, Higher Dimensional Arrays.*

In [264]:
# Your code here

# My examples are from the section: NumPy Array Search - Searching arrays
# Key feature is the np.where function, which returns the array of index of elements that matches the condition I want.

## Example 1. Searching for a specific number
arr1 = np.array([1, 2, 3, 4, 5, 4, 4]) # Example array given
search_4 = np.where(arr1 == 4)  # Search for number '4'
print(search_4)
search_1 = np.where(arr1 == 1)  # Search for number '1'
print(search_1)
print("I test to find multiple numbers with 'and' but it gave error. Maybe there is some other way..\n")


## Example 2. Finding the index of even or odd numbers
arr2 = np.array([1, 2, 3, 4, 5, 6, 7, 8]) # Example array given
search_even = np.where(arr2%2 == 0)  # Search for even numbers
print(search_even)
search_odd = np.where(arr2%2 == 1)  # Search for odd numbers
print(search_odd)
print("Be careful not to confuse the element and its index. These arrays reflect INDICES of elements, not their actual values!")

(array([3, 5, 6]),)
(array([0]),)
I test to find multiple numbers with 'and' but it gave error. Maybe there is some other way..

(array([1, 3, 5, 7]),)
(array([0, 2, 4, 6]),)
Be careful not to confuse the element and its index. These arrays reflect INDICES of elements, not their actual values!


In 2-3 sentences, describe how your function took inspiration from a section.\
\
*For my example, `make_multi_dimensional_array`, I would talk about the **NumPy Creating Arrays** section and how I took inspiration from the example **Higher Dimensional Arrays**.*

In [265]:
# Your comment here

# For my example, any_int_multiple_finder, was inspired by the fact that we can set the condition with respect to any number.
# So it does not have to be only 2, but also can be 3.
# Furthermore, we can actually make the number being diveded as a variable and make a whole function out of it!

# 2 Brianna's Module
During lecture we created and worked with a module called `even_sum.py`. Import that module here. 

In [266]:
# Your code here

import even_sum as es

Now that you have imported the module. Call the module and the first function with your own list of numbers. 

In [267]:
# Your code here

number_list = []  # This will be my list of numbers
for i in range(1, 101):
    number_list.append(i)
# I have just made a list of numbers that contain integers from 1 to 100.

# print(len(number_list))

# Call the function from the imported module and print it
print(es.sum_even_numbers(number_list))  # Matches with the expected result

2550


I have provided you a separate module called `example.py`. Import that module here.

In [268]:
# Your code here

import example as ex

With the following variables, use my module to show which of the rocket's escape!

In [269]:
rocket_velocities = np.array([
    [1000, 5000, 8000, 12000],  # Rocket 1's velocity at different times
    [2000, 6000, 9000, 11000],  # Rocket 2 "
    [3000, 3100, 3200, 3300]    # Rocket 3 "
])

mass_of_planet = 5.972e24 # kilograms
radius_of_planet = 6.371e6 # meters

In [270]:
# Your code here

print(ex.rocket_launch(rocket_velocities, mass_of_planet, radius_of_planet))

['Rocket left the planet!', 'Rocket is orbiting around the planet.', 'Rocket crashes back into the planet!']


In 2-3 sentences describe how this code follows "good coding practices" and where there is room for improvement.

In [271]:
# Your comments here

# The names of variables were very detailed, so I could recognize what that variable mean in one site.
# There were also detailed comments about what each functions would do, in terms of input and output.
# Although every lines make sense to me, it would have been slightly better if every line of functions had comments about what this line does.

# 3 Your Turn!
Now its your turn to make a module! Choose a topic from a class (could be physics, computer science, nuclear engineering, biology, astronomy, math, or an topic that interests you!) and build a module around it! Look at my module called `example.py` and base your structure around it. Your module NEEDS to include the following.

Overall:
1) Your module needs to use at least one NumPy function: https://numpy.org/devdocs/reference/routines.math.html
2) Your module needs to contain a multi-dimensional array: https://numpy.org/devdocs/reference/arrays.ndarray.html 
3) Your module needs **at least** three functions that follow good coding practices.
4) Inside your function, include comments. Don't forget to describe what the function is doing and what the inputs and outputs are.
5) Your module needs either a `for` loop or `while` loop.
6) Your module needs an `if`, `elif`, and `else` statement.
7) Your module needs at least two assignment variables (`+=`, `*=`, etc).
8) Creativity. *If it looks like you plugged this whole thing into ChatGPT, I will take off points. You can use ChatGPT to help you code, but you can't use it to just do your homework for you. That's no fun :(*

In 2-3 sentences, describe the topic of your module and its capabilities. 

In [272]:
# Your comment here

# My module, special_relativity.py is a module that contains various types of useful functions in a special relativity.
# It can calculate the Lorentz factor of an object traveling in some speed v by calling a function lorentz_factor.
# Also using that result, it can calculate another important quantities like time dilation and length contraction.
# Furthermore, it can do a Lorentz boost with any given 4-vector!

In 2-3 sentences, answer the following. What was the most challenging part of building this module? What did you learn in the process that you can apply to future coding assignments?

In [273]:
# Your comment here

# Even though my module was in the same directory with this homework file, 
# just importing it did not update any changes to my module at some point.
# I asked GPT about this and solved the problem using the library called importlib.
# This might help me in other aspect because I will be working on lot of modules and functions for my ULAB project (Dex's group).

Once your module is complete, import it here.

In [274]:
# Your code here
# Because I had some problem with loading my module contents, 
# I had no choice but to ask GPT and solved the problem by importing the following:
import importlib
import special_relativity as sr
importlib.reload(special_relativity)

<module 'special_relativity' from '/Users/lee/ulab/ulab_keondong/homework7/special_relativity.py'>

Call each of your functions in the cell below. Make sure to show the outputs! 

In [275]:
# Your code here

# Consider a particle (say, muon) that has the following attribute:
speed = 285000000 # in m s^-1, about 0.95c where c is speed of light
time_obsv = 1.8   # in µs, time interval observed for it to decay in the rest frame
length_obsv = 10  # in km, distance travelled by it observed in the rest frame 
motion_vector = [time_obsv, length_obsv, 2, 3]  # Spacetime component and position vector


# Lorentz factor of the particle
print(f"For a particle with speed {speed}m/s, its Lorentz factor is {sr.lorentz_factor(speed)}.\n")

# Time dilation in the particle's frame
print(f"Due to its relativistic motion, it observed its own decay time to be longer, from {time_obsv}µs to {sr.time_dilation(time_obsv, speed)}µs.\n")

# Length contraction in the particle's frame
print(f"Due to the same reason, its distance travelled contracts from {length_obsv}km to {sr.length_contraction(length_obsv, speed)}km.\n")

# Lorentz boost to the particle's frame
print(f"For a specific object which has {motion_vector} four-vector and speed {speed}, its lorentz boost gives {sr.lorentz_boost(motion_vector, speed)}.")  
# The result should be different because it also considers relationship of spacetime

For a particle with speed 285000000m/s, its Lorentz factor is 3.2026.

Due to its relativistic motion, it observed its own decay time to be longer, from 1.8µs to 5.7647µs.

Due to the same reason, its distance travelled contracts from 10km to 3.1225km.

For a specific object which has [1.8, 10, 2, 3] four-vector and speed 285000000, its lorentz boost gives [-25, 27, 2, 3].


# 4 Proper Submission
To recieve full credit for this assignment make sure you do the following:

1) Copy this homework assignment from the `ulab_2024` repository into **YOUR** local `homework7` branch. It will contain this notebook and an additional file called `example.py`. 
   
2) Follow the tasks. Make sure to run all the cells so that **all** output is visible. You will get points taken off if your ouputs are not shown!

3) Add/commit/push this notebook and **ANY** modules (so you should have `example.py` and your module) used in this homework assignment to your remote `homework7` branch. Make sure to have NOTHING else in your branch (i.e. no previous homeworks or lecture notes).

4) Do the following:
- Take a screenshot of moving **into or out** of your `homework7` brach, call it `hw7_branch`.
- Take a screenshot of calling `ls` in your `homework7` branch, it should only contain items relevent to homework 7, call it `hw7_ls`.
- Take a screenshot of adding this assignment to your local `homework7` branch, call it `hw7_add`.
- Take a screenshot of committing this assignment to your local `homework7` branch, call it `hw7_commit`.
- Take a screenshot of pushing this assignment to your remote `homework7` branch, call it `hw7_push`. 

6) Include these screenshots in your `homework7` branch. Upload your `homework7` branch to Gradescope!